---
name: Build Matrix of Binaries
            
'on':
        push:
            branches:
                - main
                - build-*
            tags:
                - "v[0-9]+.[0-9]+.[0-9]+"    

env: 
    TARI_TARGET_NETWORK: esme
    TARI_NETWORK: esme

jobs:
    build:
        runs-on: ${{ matrix.platform }}
        strategy:
            matrix:
              include:
                #  - platform: 'ubuntu-20.04'
                #    args: ''
                  - platform: 'windows-2019'
                    # args: ''
                  - platform: 'macos-latest'
                    # args: '--verbose --target universal-apple-darwin'

                  
        steps:
            - uses: actions/checkout@v4
            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable
            - uses: Jimver/cuda-toolkit@v0.2.14
              if: startsWith(runner.os,'Windows')
              with:
                 method: network
                 sub-packages: '["nvcc", "cudart"]'
            - name: Install dependencies (macOS)
              if: startsWith(runner.os,'macOS')
              run: |
                   # openssl, cmake and autoconf already installed
                   brew install zip coreutils automake protobuf libtool
              
            - name: Install Windows dependencies
              if: startsWith(runner.os,'Windows')
              run: |
                   #  vcpkg.exe install sqlite3:x64-windows zlib:x64-windows
                   # Bug in choco - need to install each package individually
                   choco upgrade llvm -y
                   choco upgrade protoc -y     

            - name: build opencl (windows)
              if: startsWith(runner.os,'Windows')
              run: |
                cargo build --release --features "opencl3" --bin xtrgpuminer
            - uses: actions/upload-artifact@v4
              if: startsWith(runner.os,'Windows')
              with:
                name: xtr_miner_opencl_windows
                path: target/release/xtrgpuminer.exe

            - name: build cuda (windows)
              if: startsWith(runner.os,'Windows')
              run: |
                  cargo build --release --features "nvidia" --bin xtrgpuminer
            - uses: actions/upload-artifact@v4
              if: startsWith(runner.os,'Windows')
              with:
                  name: xtr_miner_cuda_windows
                  path: target/release/xtrgpuminer.exe    


            - name: build opencl (macos)
              if: startsWith(runner.os,'macOs')
              run: |
                    cargo build --release --features "opencl3" --bin xtrgpuminer
            - uses: actions/upload-artifact@v4
              if: startsWith(runner.os,'macOs')
              with:
                    name: xtr_miner_opencl_macos
                    path: target/release/xtrgpuminer       

    create-release:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      steps:
        - name: Download binaries
          uses: actions/download-artifact@v4
        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            artifacts: "xtr_*/**/*"
            token: ${{ secrets.GITHUB_TOKEN }}
            prerelease: true
            draft: true            